#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "jupyterlab"
name = "JupyterLab"
description.en = "Interactive development environment for notebooks"
description.fr = "Environnement de développement interactif pour notebooks"

#https://pypi.org/project/jupyterlab/
version = "4.2.5~ynh2"

maintainers = []

[upstream]
license = "BSD-3-Clause"
website = "https://jupyter.org"
demo = "https://mybinder.org/v2/gh/jupyterlab/jupyterlab-demo/master?urlpath=lab/tree/demo"
admindoc = "https://jupyterlab.readthedocs.io/en/stable/"
code = "https://github.com/jupyterhub/jupyterhub"

[integration]
yunohost = ">= 11.2.30"
helpers_version = "2.1"
architectures = "all"
multi_instance = false

ldap = true

sso = false

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/jupyterlab"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

    [install.admin]
    type = "user"

    [install.enable_terminal]
    ask.en = "Enable terminal in the lab?"
    ask.fr = "Activer le terminal dans le lab ?"
    type = "boolean"
    default = true

[resources]
    [resources.sources.main]
    url = "https://github.com/jupyterlab/jupyterlab/archive/refs/tags/v4.2.5.tar.gz"
    sha256 = "2a67111b23a05aa8ff44a0f1663c983980471d24910157a0abbee06e808f4eb0"
    # Only used for autoupdate, code will checkout the commit
    prefetch = false

    autoupdate.strategy = "latest_github_release"

    [resources.system_user]

    [resources.install_dir]
    # Using /opt because /var/www has ACLs that prevent users to access it
    dir = "/opt/__APP__"

    [resources.permissions]
    main.url = "/"

    [resources.ports]
    main.default = 8080
    hub.default = 8081
    http_proxy.default = 8082

    [resources.apt]
    packages = "python3-dev, python3-pip, python3-venv, pipenv"

    [resources.apt.extras.yarn]
    repo = "deb https://dl.yarnpkg.com/debian/ stable main"
    key = "https://dl.yarnpkg.com/debian/pubkey.gpg"
    packages = ["yarn"]
