#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/tests.v1.schema.json

test_format = 1.0

[default]

    # ------------
    # Tests to run
    # ------------

    exclude = ["install.multi"]

    # -------------------------------
    # Default args to use for install
    # -------------------------------

    args.enable_terminal = "true"

    # -------------------------------
    # Commits to test upgrade from
    # -------------------------------

    test_upgrade_from.c277fe83ccd64f5d7d2268cbd349592a42c62028.name = "Upgrade from 4.2.5~ynh1"
